#!/bin/bash
# install -- Start a new Nuweb project
# 20180201 Paul Huygen
thisdirname=${PWD##*/}
projname=`cd .. && echo ${PWD##*/}`


function usage () {
cat <<EOF
Usage: install -a <author> -t <title>
e.g. "install -a "Paul Huygen" -t "Program to demonstrate nuweb\_initscripts"
EOF
}

# Options:
# - Author
# - Doctitle
unset author
unset title
while getopts "h?va:t:" opt; do
    case "$opt" in
    h|\?)
        usage
        exit 0
        ;;
    v)  verbose=1
        ;;
    a)  author=$OPTARG
        ;;
    t)  title=$OPTARG
        ;;
    esac
done

if [ -z ${author+x} ]
then 
  read -p "author: "  author
fi

if [ -z ${title+x} ]
then 
  read -p "title: "  title
fi


cat instm4.tpl \
    | sed s/TheAuthor/"$author"/g \
    | sed s/TheDocName/"$projname"/g \
    | sed s/TheDocTitle/"$title"/g \
    > ../inst.m4
#cat instm4.tpl | sed $sed1  | sed $sed2 > inst.m4

cp a_template.w ../a_"$projname".w
cp thelatexheader.tex ../
cd ..
m4 -P $projname/Makefile.m4 >Makefile
cp $projname/w2pdf .
cd $thisdirname

#
# HTML
#
mkdir -p ../html
cd ../html
cp ../$thisdirname/w2html .
ln -s ../thelatexheader.tex ./


